FROM debian:trixie AS build

RUN apt update -y && apt upgrade -y && \
    apt install -y build-essential cmake ninja-build locales-all pkgconf git file dpkg-dev zlib1g-dev \
                   libasound2-dev libcurl4-openssl-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

# Make the build directory and the output directory
RUN mkdir build /package

# Build it
RUN cmake -S controller/ -B build -G Ninja
RUN cmake --build build

# Make the package
RUN cd build && cpack -G DEB && cp *.deb /package
